version: '3'
services:
  app:
    build: .
    ports:
    - "127.0.0.1:5000:5000"
    environment:
    - PORT=5000
    links:
    - db
    restart: always
  db:
    image: postgres:9-alpine
    ports:
    - "127.0.0.1:5432:5432"
    environment:
    - POSTGRES_USER=sparta
    - POSTGRES_PASSWORD=sparta
    restart: always
